### ISSUE TITLE
Residential status

### ISSUE THREAD

**Issue by balupton** [the-basetrip/country-information#5]
For tax purposes it is useful to know when a country considers a foreigner a resident. It would be great if this information was provided by The Basetrip so that digital nomads can better access the tax implications of their travel plans.

---

For instance in India, if you are on a Student Visa, Medical Visa, Research Visa and Employment Visa, and stay more than 180 days, than you must register as a resident within 14 days of arrival.
https://en.wikipedia.org/wiki/Foreigner_registration_in_India

You will then be taxed on local and foreign income:
https://en.m.wikipedia.org/wiki/International_taxation

**Comment by svenkapudija** [comment]
As we are more focusing on the business travel, we see the point in making these available, however, the complexity of these is verging on the visa requirement complexity which is quite extensive and changing on a daily basis. Because of that, we will not (can not) include it at this time. Sorry about that.
